<a href="https://colab.research.google.com/github/bwowby/DS/blob/master/statsmodel_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import io
import statsmodels.api

def main():
    (N, X, Y) = read_data()
    results = do_simple_regression(N, X, Y)
    print(results.summary())
    print("pvalues", results.pvalues)
    print(results.params)
def read_data():
    # 1
    N = int(input().strip())
    X = np.array([])
    Y = np.array([])
    for i in range(N):
        tmp = input()
        X = np.append(X,int(tmp.split(" ")[0]))
        Y = np.append(Y,int(tmp.split(" ")[1]))
        print(X,Y)
    return (N, X, Y)

def do_simple_regression(N, X, Y):
    # 2
    X = X.T
    X = statsmodels.api.add_constant(X)
    results = statsmodels.api.OLS(Y,X).fit()
    return results

if __name__ == "__main__":
    main()


5
1 1
[1.] [1.]
2 4
[1. 2.] [1. 4.]
3 9
[1. 2. 3.] [1. 4. 9.]
4 16
[1. 2. 3. 4.] [ 1.  4.  9. 16.]
5 25
[1. 2. 3. 4. 5.] [ 1.  4.  9. 16. 25.]
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.963
Model:                            OLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     77.14
Date:                Fri, 02 Oct 2020   Prob (F-statistic):            0.00311
Time:                        10:40:07   Log-Likelihood:                -9.6687
No. Observations:                   5   AIC:                             23.34
Df Residuals:                       3   BIC:                             22.56
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025 

/usr/local/lib/python3.6/dist-packages/statsmodels/stats/stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
