<a href="https://colab.research.google.com/github/bwowby/DS/blob/master/pytorch_tutorial/tensor_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
type(x_data)

torch.Tensor

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [7]:
torch.ones(x_data.shape)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[0.6004, 0.1758],
        [0.8942, 0.8260]])

In [16]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor, ones_tensor, zeros_tensor)
print(rand_tensor.shape, ones_tensor.shape, zeros_tensor.shape)

tensor([[0.7488, 0.8605, 0.1997],
        [0.4396, 0.4511, 0.1182]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3]) torch.Size([2, 3]) torch.Size([2, 3])


## tensor attribute

In [18]:
tensor = torch.rand(3,4)

print(f"shape of tensor : {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device tensor : {tensor.device}")

shape of tensor : torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor : cpu


## tensor operation
기본적으로 텐서는 cpu에서 생성됨.
to() 메소드를 사용하면 gpu로 텐서를 명시적으로 이동할 수 있음.

In [21]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py'>

In [19]:
torch.cuda.is_available()

False

In [20]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [22]:
tensor.device

device(type='cpu')

## numpy식 표준 인덱싱 & 슬라이싱

In [48]:
tensor = torch.ones(4,4)
print(f"First row : {tensor[0]}")
print(f"First column: {tensor[:1]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column : {tensor[...,-1]}")

tensor[:,0] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column: tensor([[1., 1., 1., 1.]])
First column: tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.]])


In [ ]:
tensor[:,1] = 0

In [47]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [51]:
np.stack([tensor, tensor, tensor]).shape

(3, 4, 4)

In [52]:
np.hstack([tensor, tensor, tensor]).shape

(4, 12)

In [53]:
np.vstack([tensor, tensor, tensor]).shape

(12, 4)

## 산술연산